In [1]:
from scipy.spatial import distance
import numpy as np
from sympy import *
import math

**Angles**

In [37]:
x = np.array([1, 1])
y = np.array([1, 2])

In [38]:
xT = x.T
xT

array([1, 1])

In [39]:
yT = y.T
yT

array([1, 2])

In [45]:
cos_w = np.dot(xT,y) / math.sqrt(np.dot(xT, x) * np.dot(yT, y))
cos_w

0.9486832980505138

In [46]:
np.arccos(nom)

0.3217505543966423

**Question 2**

In [47]:
x = np.array([1, 1])
y = np.array([-1, 1])

In [48]:
xT = x.T
xT

array([1, 1])

In [49]:
yT = y.T
yT

array([-1,  1])

In [50]:
cos_a = np.dot(xT,y) / math.sqrt(np.dot(xT, x) * np.dot(yT, y))
cos_a

0.0

**Question 3**

In [55]:
x = np.array([1, 1])
x

array([1, 1])

In [65]:
xT = x.T

In [75]:
y = np.array([-1, 1 ])
y

array([-1,  1])

In [68]:
yT = y.T

In [69]:
matrix = np.array([[2, 0],
                   [0, 1]])
matrix

array([[2, 0],
       [0, 1]])

In [73]:
xm = np.dot(x, matrix)
xm

array([2, 1])

In [76]:
xm_y = np.dot(xm, y)
xm_y

-1

In [77]:
xxm = np.dot(x, matrix)
xxm

array([2, 1])

In [78]:
xxm_x = np.dot(xxm, xT)
xxm_x

3

In [83]:
yym = np.dot(y, matrix)
yym

array([-2,  1])

In [95]:
yym_y = np.dot(yym, y)
yym_y

3

In [97]:
cos_b = xm_y / math.sqrt(xxm_x * yym_y)
cos_b

-0.3333333333333333

In [98]:
ans = np.arccos(cos_b)
ans

1.9106332362490186

**Angles between vectors using a non-standard inner product**

In [111]:
x = np.array([1, 1])
x

array([1, 1])

In [112]:
y = np.array([-1, 1])
y

array([-1,  1])

In [113]:
xT = x.T
xT

array([1, 1])

In [114]:
matrix = np.array([[2, -1],
                   [-1, 4]])
matrix

array([[ 2, -1],
       [-1,  4]])

In [115]:
xm = np.dot(xT, matrix)
xm

array([1, 3])

In [116]:
xm_y = np.dot(xm, y)
xm_y

2

In [117]:
xTm_x = np.dot(xm, x)
xTm_x

4

In [118]:
yTm = np.dot(yT, matrix)
yTm

array([3, 2])

In [121]:
yTm_y = np.dot(yTm, yT)
yTm_y

8

In [122]:
cos_c = xm_y / math.sqrt(xTm_x * yTm_y)
cos_c

0.35355339059327373

In [124]:
ans = np.arccos(cos_c)
ans

1.2094292028881888

**Question 2**

In [125]:
x = np.array([0, -1])
x

array([ 0, -1])

In [126]:
y = np.array([1, 1])
y

array([1, 1])

In [127]:
xT = x.T
xT

array([ 0, -1])

In [128]:
yT = y.T
yT

array([1, 1])

In [129]:
matrix = np.array([[1,  -1/2],
                   [-1/2, 5]])
matrix

array([[ 1. , -0.5],
       [-0.5,  5. ]])

In [130]:
xm = np.dot(xT, matrix)
xm

array([ 0.5, -5. ])

In [131]:
xm_y = np.dot(xm, y)
xm_y

-4.5

In [132]:
xTm = np.dot(xT, matrix)
xTm

array([ 0.5, -5. ])

In [133]:
xTm_x = np.dot(xTm, x)
xTm_x

5.0

In [134]:
yTm = np.dot(yT, matrix)
yTm

array([0.5, 4.5])

In [136]:
yTm_yT = np.dot(yTm, yT)
yTm_yT

5.0

In [140]:
cos_d = xm_y / math.sqrt(xTm_x * yTm_yT)
cos_d

-0.9

In [142]:
ans2 = np.arccos(cos_d)
ans2

2.6905658417935308

**Question 3**

In [143]:
x = np.array([ 2,  2])
y = np.array([-2, -2])

In [144]:
xT = x.T
xT

array([2, 2])

In [145]:
yT = y.T
yT

array([-2, -2])

In [146]:
matrix = np.array([[2, 1],
                   [1, 4]])
matrix

array([[2, 1],
       [1, 4]])

In [147]:
xTm = np.dot(xT, matrix)
xTm

array([ 6, 10])

In [148]:
xTm_y = np.dot(xTm, y)
xTm_y

-32

In [149]:
xTm_x = np.dot(xTm, x)
xTm_x

32

In [150]:
yTm = np.dot(yT, matrix)
yTm

array([ -6, -10])

In [151]:
yTm_yT = np.dot(yTm, yT)
yTm_yT

32

In [152]:
cos_e = xTm_y / math.sqrt(xTm_x * yTm_yT)
cos_e

-1.0

In [153]:
np.arccos(cos_e)

3.141592653589793

**Question 4**

In [154]:
x = np.array([1, 1])
x

array([1, 1])

In [157]:
xT = x.T
xT

array([1, 1])

In [155]:
y = np.array([1, -1])
y

array([ 1, -1])

In [158]:
yT = y.T
yT

array([ 1, -1])

In [159]:
matrix = np.array([[1, 0],
                   [0, 5]])
matrix

array([[1, 0],
       [0, 5]])

In [161]:
xTm = np.dot(xT, matrix)
xTm

array([1, 5])

In [162]:
xTm_y = np.dot(xTm, y)
xTm_y

-4

In [163]:
xTm_x = np.dot(xTm, x)
xTm_x

6

In [164]:
yTm = np.dot(yT, matrix)
yTm

array([ 1, -5])

In [165]:
yTm_yT = np.dot(yTm, yT)
yTm_yT

6

In [166]:
cos_t = xTm_y / math.sqrt(xTm_x * yTm_yT)
cos_t

-0.6666666666666666

In [167]:
ans5 = np.arccos(cos_t)
ans5

2.300523983021863

**Question 5**

In [168]:
x = np.array([1, 1, 1])
y = np.array([2, -1, 0])

In [169]:
xT = x.T
xT

array([1, 1, 1])

In [170]:
yT = y.T
yT

array([ 2, -1,  0])

In [171]:
matrix = np.array([[1,  0,  0],
                   [0,  2, -1],
                   [0, -1, 3]])
matrix

array([[ 1,  0,  0],
       [ 0,  2, -1],
       [ 0, -1,  3]])

In [172]:
xTm = np.dot(xT, matrix)
xTm

array([1, 1, 2])

In [173]:
xTm_y = np.dot(xTm, y)
xTm_y

1

In [174]:
xTm_x = np.dot(xTm, x)
xTm_x

4

In [175]:
yTm = np.dot(yT, matrix)
yTm

array([ 2, -2,  1])

In [176]:
yTm_yT = np.dot(yTm, yT)
yTm_yT

6

In [177]:
cos_g = xTm_y / math.sqrt(xTm_x * yTm_yT)
cos_g

0.20412414523193154

In [179]:
ans0 = np.arccos(cos_g)
ans0

1.3652273956337226