In [1]:
from sympy import *
import math
import numpy as np

# Multivariate Chain Rule

In [2]:
u1, u2, f, x, t, u, x1, x2, e, x3 = symbols("u1 u2 f x t u x1 x2 e x3")

In [33]:
fx = 5*x
fx

5*x

In [34]:
xu = 1 - u
xu

1 - u

In [35]:
ut = t**2
ut

t**2

In [36]:
xut = xu.subs(u, ut)
xut

1 - t**2

In [37]:
ft = fx.subs(x, xut)
ft

5 - 5*t**2

In [38]:
diff_ft = diff(ft, t)
diff_ft

-10*t

**Question 1**

In [42]:
fx = x1**2 * x2**2 + x1 * x2
fx

x1**2*x2**2 + x1*x2

In [55]:
dfx1 = diff(fx, x1)
dfx1

2*x1*x2**2 + x2

In [56]:
dfx2 = diff(fx, x2)
dfx2

2*x1**2*x2 + x1

In [57]:
Matrix_fx = Matrix([[dfx1, dfx2]])
Matrix_fx

Matrix([[2*x1*x2**2 + x2, 2*x1**2*x2 + x1]])

In [43]:
x1t = 1 - t**2
x1t

1 - t**2

In [44]:
x2t = 1 + t**2
x2t

t**2 + 1

In [51]:
dx1t = diff(x1t, t)
dx1t

-2*t

In [52]:
dx2t = diff(x2t, t)
dx2t

2*t

In [59]:
dxt = Matrix([[dx1t],
              [dx2t]])
dxt

Matrix([
[-2*t],
[ 2*t]])

In [95]:
print(Matrix_fx, dxt)

Matrix([[2*x1*x2**2 + x2, 2*x1**2*x2 + x1]]) Matrix([[-2*t], [2*t]])


**Question 2**

In [62]:
fx = x1**3*cos(x2)*e**x3
fx

e**x3*x1**3*cos(x2)

In [63]:
x1t = 2*t
x1t

2*t

In [64]:
x2t = 1 - t**2
x2t

1 - t**2

In [65]:
x3t = e**t
x3t

e**t

In [66]:
fx1 = diff(fx, x1)
fx1

3*e**x3*x1**2*cos(x2)

In [67]:
fx2 = diff(fx, x2)
fx2

-e**x3*x1**3*sin(x2)

In [68]:
fx3 = diff(fx, x3)
fx3

e**x3*x1**3*log(e)*cos(x2)

In [69]:
df_dx = Matrix([[fx1, fx2, fx3]]) 
df_dx

Matrix([[3*e**x3*x1**2*cos(x2), -e**x3*x1**3*sin(x2), e**x3*x1**3*log(e)*cos(x2)]])

In [70]:
dx1 = diff(x1t, t)
dx1

2

In [71]:
dx2 = diff(x2t, t)
dx2

-2*t

In [72]:
dx3 = diff(x3t, t)
dx3

e**t*log(e)

In [73]:
dx_dt = Matrix([[dx1],
                [dx2],
                [dx3]])
dx_dt

Matrix([
[          2],
[       -2*t],
[e**t*log(e)]])

In [ ]:
print()

**Question 3**

In [74]:
fx = x1**2 - x2**2
fx

x1**2 - x2**2

In [75]:
fx1 = diff(fx, x1)
fx1

2*x1

In [76]:
fx2 = diff(fx, x2)
fx2

-2*x2

In [78]:
df_dx = Matrix([[fx1, fx2]])
df_dx

Matrix([[2*x1, -2*x2]])

In [80]:
x1_u1u2 = 2*u1 + 3*u2
x1_u1u2

2*u1 + 3*u2

In [81]:
x2_u1u2 = 2*u1 - 3*u2
x2_u1u2

2*u1 - 3*u2

In [96]:
u1t = cos(t/2)
u1t

cos(t/2)

In [97]:
u2t = sin(2*t)
u2t

sin(2*t)

In [84]:
dx1_u1 = diff(x1_u1u2, u1)
dx1_u1

2

In [86]:
dx1_u2 = diff(x1_u1u2, u2)
dx1_u2

3

In [87]:
dx2_u1 = diff(x2_u1u2, u1)
dx2_u1

2

In [89]:
dx2_u2 = diff(x2_u1u2, u2)
dx2_u2

-3

In [90]:
dx_du = Matrix([[dx1_u1, dx1_u2],
                [dx2_u1, dx2_u2]])
dx_du

Matrix([
[2,  3],
[2, -3]])

In [99]:
du1t = diff(u1t, t)
du1t

-sin(t/2)/2

In [100]:
du2t = diff(u2t, t)
du2t

2*cos(2*t)

In [101]:
du_dt = Matrix([[du1t],
                [du2t]])
du_dt

Matrix([
[-sin(t/2)/2],
[ 2*cos(2*t)]])

**Question 4**

In [3]:
fx = cos(x1)*sin(x2)
fx

sin(x2)*cos(x1)

In [4]:
x1_u1u2 = 2*u1**2 + 3*u2**2 - u2
x1_u1u2

2*u1**2 + 3*u2**2 - u2

In [5]:
x2_u1u2 = 2*u1 - 5*u2**3
x2_u1u2

2*u1 - 5*u2**3

In [6]:
u1t = e**(t/2)
u1t

e**(t/2)

In [7]:
u2t = e**(-2*t)
u2t

e**(-2*t)

In [9]:
df_dx1 = diff(fx, x1)
df_dx1

-sin(x1)*sin(x2)

In [10]:
df_dx2 = diff(fx, x2)
df_dx2

cos(x1)*cos(x2)

In [11]:
matrix_fx = Matrix([[df_dx1, df_dx2]])
matrix_fx

Matrix([[-sin(x1)*sin(x2), cos(x1)*cos(x2)]])

In [12]:
x1_u1 = diff(x1_u1u2, u1)
x1_u1

4*u1

In [13]:
x1_u2 = diff(x1_u1u2, u2)
x1_u2

6*u2 - 1

In [14]:
x2_u1 = diff(x2_u1u2, u1)
x2_u1

2

In [15]:
x2_u2 = diff(x2_u1u2, u2)
x2_u2

-15*u2**2

In [16]:
dx_du = Matrix([[x1_u1, x1_u2],
                [x2_u1, x2_u2]])
dx_du

Matrix([
[4*u1,  6*u2 - 1],
[   2, -15*u2**2]])

In [17]:
du1t = diff(u1t, t)
du1t

e**(t/2)*log(e)/2

In [18]:
du2t = diff(u2t, t)
du2t

-2*e**(-2*t)*log(e)

In [19]:
du_dt = Matrix([[du1t, du2t]])
du_dt

Matrix([[e**(t/2)*log(e)/2, -2*e**(-2*t)*log(e)]])

**Question 5**

In [20]:
fx = sin(x1)*cos(x2)*e**x3
fx

e**x3*sin(x1)*cos(x2)

In [21]:
x1_u1u2 = sin(u1) + cos(u2)
x1_u1u2

sin(u1) + cos(u2)

In [22]:
x2_u1u2 = cos(u1) - sin(u2)
x2_u1u2

-sin(u2) + cos(u1)

In [24]:
x3_u1u2 = e**(u1+u2)
x3_u1u2

e**(u1 + u2)

In [25]:
u1t = 1 + (t/2)
u1t

t/2 + 1

In [26]:
u2t = 1 - (t/2)
u2t

1 - t/2

In [27]:
dfx1 = diff(fx, x1)
dfx1

e**x3*cos(x1)*cos(x2)

In [28]:
dfx2 = diff(fx, x2)
dfx2

-e**x3*sin(x1)*sin(x2)

In [29]:
dfx3 = diff(fx, x3)
dfx3

e**x3*log(e)*sin(x1)*cos(x2)

In [30]:
df_dx = Matrix([[dfx1, dfx2, dfx3]])
df_dx

Matrix([[e**x3*cos(x1)*cos(x2), -e**x3*sin(x1)*sin(x2), e**x3*log(e)*sin(x1)*cos(x2)]])

In [31]:
x1_u1 = diff(x1_u1u2, u1)
x1_u1

cos(u1)

In [32]:
x1_u2 = diff(x1_u1u2, u2)
x1_u2

-sin(u2)

In [33]:
x2_u1 = diff(x2_u1u2, u1)
x2_u1

-sin(u1)

In [34]:
x2_u2 = diff(x2_u1u2, u2)
x2_u2

-cos(u2)

In [35]:
x3_u1 = diff(x3_u1u2, u1)
x3_u1

e**(u1 + u2)*log(e)

In [36]:
x3_u2 = diff(x3_u1u2, u2)
x3_u2

e**(u1 + u2)*log(e)

In [38]:
x1x2x3 = Matrix([[x1_u1, x1_u2],
                 [x2_u1, x2_u2],
                 [x3_u1, x3_u2]])
x1x2x3

Matrix([
[            cos(u1),            -sin(u2)],
[           -sin(u1),            -cos(u2)],
[e**(u1 + u2)*log(e), e**(u1 + u2)*log(e)]])

In [39]:
du1t = diff(u1t, t)
du1t

1/2

In [40]:
du2t = diff(u2t, t)
du2t

-1/2

In [41]:
u1u2 = Matrix([[du1t, du2t]])
u1u2

Matrix([[1/2, -1/2]])

# Simple Artificial Neural Networks

In [35]:
a = np.tanh
w1 = -5
b1 = 5

In [36]:
def a1(a0):
    return a(w1 * a0 + b1)
a1(0)

0.9999092042625951

In [37]:
w2 = 0
b2 = 5

In [38]:
def a2(a0):
    return a(w2 * a0 + b2)
a2(0)

0.9999092042625951

In [39]:
a2(0) == a1(0)

True

**Question 2**


In [44]:
sigma = np.tanh

In [58]:
W = np.mat([[-2, 4, -1],
            [6, 0,  -3]])
W

matrix([[-2,  4, -1],
        [ 6,  0, -3]])

In [62]:
b = np.mat([0.1, -2.5])
b

matrix([[ 0.1, -2.5]])

In [67]:
a = np.mat([0.3, 0.4, 0.1])
a

matrix([[0.3, 0.4, 0.1]])

In [69]:
a1_0 = (np.tanh(W*a.T + b.T)).T
a1_0

matrix([[ 0.76159416, -0.76159416]])

# Training Neural Networks

In [70]:
σ = np.tanh
w1 = 1.3
b1 = -0.1

In [71]:
def a1(a0):
    z = w1 * a0 + b1
    return σ(z)

In [72]:
x = 0
result = a1(x)
z = (result - 1) ** 2
print(z)

1.209269698402472


**Question 2**

In [74]:
# First define our sigma function.
sigma = np.tanh

# Next define the feed-forward equation.
def a1 (w1, b1, a0):
    z = w1 * a0 + b1
    return sigma(z)

# The individual cost function is the square of the difference between
# the network output and the training data output.
def C (w1, b1, x, y):
    return (a1(w1, b1, x) - y)**2

# This function returns the derivative of the cost function with
# respect to the weight.
def dCdw (w1, b1, x, y):
    z = w1 * x + b1
    dCda = 2 * (a1(w1, b1, x) - y) # Derivative of cost with activation
    dadz = 1/np.cosh(z)**2 # derivative of activation with weighted sum z
    dzdw = x # derivative of weighted sum z with weight
    return dCda * dadz * dzdw # Return the chain rule product.

# This function returns the derivative of the cost function with
# respect to the bias.
# It is very similar to the previous function.
# You should complete this function.
def dCdb (w1, b1, x, y):
    z = w1 * x + b1
    dCda = 2 * (a1(w1, b1, x) - y)
    dadz = 1/np.cosh(z)**2
    """ Change the next line to give the derivative of
    the weighted sum, z, with respect to the bias, b. """
    dzdb = 1
    return dCda * dadz * dzdb

"""Test your code before submission:"""
# Let's start with an unfit weight and bias.
w1 = 2.3
b1 = -1.2
# We can test on a single data point pair of x and y.
x = 0
y = 1
# Output how the cost would change
# in proportion to a small change in the bias
print( dCdb(w1, b1, x, y) )

-1.1186026425530913


**Question 3**

In [76]:
# Define the activation function.
sigma = np.tanh

# Let's use a random initial weight and bias.
W = np.array([[-0.94529712, -0.2667356 , -0.91219181],
              [ 2.05529992,  1.21797092,  0.22914497]])
b = np.array([ 0.61273249,  1.6422662 ])

# define our feed forward function
def a1 (a0) :
  # Notice the next line is almost the same as previously,
  # except we are using matrix multiplication rather than scalar multiplication
  # hence the '@' operator, and not the '*' operator.
  z = W @ a0 + b
  # Everything else is the same though,
  return sigma(z)

# Next, if a training example is,
x = np.array([0.1, 0.5, 0.6])
y = np.array([0.25, 0.75])

# Then the cost function is,
d = a1(x) - y # Vector difference between observed and expected activation
C = d @ d # Absolute value squared of the difference.
print(C)

0.22604860306887126


**Question 4**

In [3]:
# Define the activation function.
sigma = np.tanh

# Let's use a random initial weight and bias.
W = np.array([[-0.94529712, -0.2667356 , -0.91219181],
              [ 2.05529992,  1.21797092,  0.22914497]])
b = np.array([ 0.61273249,  1.6422662 ])

# define our feed forward function
def a1 (a0) :
  # Notice the next line is almost the same as previously,
  # except we are using matrix multiplication rather than scalar multiplication
  # hence the '@' operator, and not the '*' operator.
  z = W @ a0 + b
  # Everything else is the same though,
  return sigma(z)

# Next, if a training example is,
x = np.array([0.7, 0.6, 0.2])
y = np.array([0.9, 0.6])

# Then the cost function is,
d = a1(x) - y # Vector difference between observed and expected activation
C = d @ d # Absolute value squared of the difference.
print(C)

1.7788340952508743
