# projection onto 1D subspaces

In [66]:
import numpy as np
import math
from sympy import *

In [2]:
b = np.array([2, 1])
x = np.array([1, 2])

In [3]:
xT = x.T
xT

array([1, 2])

In [27]:
proj =(np.dot(xT, b) / (np.linalg.norm(b)**2)) * b
proj

array([1.6, 0.8])

**Question 2**

In [31]:
b = np.array([1, 2, 2])
b

array([1, 2, 2])

In [32]:
bT = b.T
bT

array([1, 2, 2])

In [37]:
np.linalg.norm(b) ** 2

9.0

**Question 3**

In [39]:
x = np.array([1, 1, 1])
x

array([1, 1, 1])

In [41]:
xT = x.T
xT

array([1, 1, 1])

In [40]:
b = np.array([3, 0, 4])
b

array([3, 0, 4])

In [45]:
proj =(np.dot(xT, b) / (np.linalg.norm(b)**2)) * b
proj

array([0.84, 0.  , 1.12])

**Question 3**

In [49]:
c = np.array([1, 1, 1])
d = np.array([5, 10, 10])

In [50]:
def projection(x, on):
    return np.dot(x, on) / np.dot(on, on) * on
projection(c, d)

array([0.55555556, 1.11111111, 1.11111111])

In [53]:
def rejection(x, on):
    return x - projection(x, on)
rejection(c, d)

array([ 0.44444444, -0.11111111, -0.11111111])

In [54]:
def reconstruction(x, on):
    return norm(rejection(x, on))
reconstruction(c, d)

0.4714045207910317

# projection onto a 2D subspace

In [94]:
x =  Matrix([2, 1, 1])
b1 = Matrix([1, 2, 0])
b2 = Matrix([1, 1, 0])

In [97]:
B = Matrix([[b1, b2]])
B

Matrix([
[1, 1],
[2, 1],
[0, 0]])

In [99]:
BTx = B.T@x
BTx

Matrix([
[4],
[3]])

In [100]:
BTB = B.T@B
BTB

Matrix([
[5, 3],
[3, 2]])

In [102]:
lamda = BTB.inv() @ BTx
lamda

Matrix([
[-1],
[ 3]])

In [109]:
proj = lamda[0]*b1 + lamda[1]*b2
proj

Matrix([
[2],
[1],
[0]])

# Project 3D data onto a 2D subspace

In [110]:
x = Matrix([6, 0, 0])
x

Matrix([
[6],
[0],
[0]])

In [111]:
b1 = Matrix([1, 1, 1])
b1

Matrix([
[1],
[1],
[1]])

In [112]:
b2 = Matrix([0, 1, 2])
b2

Matrix([
[0],
[1],
[2]])

In [113]:
B = Matrix([[b1, b2]])
B

Matrix([
[1, 0],
[1, 1],
[1, 2]])

In [114]:
BTx = B.T@x
BTx

Matrix([
[6],
[0]])

In [115]:
BTB = B.T@B
BTB

Matrix([
[3, 3],
[3, 5]])

In [117]:
lamda = BTB.inv()@BTx
lamda

Matrix([
[ 5],
[-3]])

In [118]:
proj = lamda[0]*b1 + lamda[1]*b2
proj

Matrix([
[ 5],
[ 2],
[-1]])

**Question 2**

In [119]:
x  = Matrix([3, 2, 2])
b1 = Matrix([1, 0, 0])
b2 = Matrix([0, 1, 1])

In [120]:
B = Matrix([[b1, b2]])
B

Matrix([
[1, 0],
[0, 1],
[0, 1]])

In [121]:
BTx = B.T@x
BTx

Matrix([
[3],
[4]])

In [122]:
BTB = B.T@B
BTB

Matrix([
[1, 0],
[0, 2]])

In [123]:
lamda = BTB.inv()@BTx
lamda

Matrix([
[3],
[2]])

In [124]:
proj = lamda[0]*b1 + lamda[1]*b2
proj

Matrix([
[3],
[2],
[2]])

**Question 3**

In [125]:
x  = Matrix([12, 0, 0])
b1 = Matrix([1, 1, 1])
b2 = Matrix([0, 1, 2])

In [126]:
B = Matrix([[b1, b2]])
B

Matrix([
[1, 0],
[1, 1],
[1, 2]])

In [127]:
BTx = B.T@x
BTx

Matrix([
[12],
[ 0]])

In [128]:
BTB = B.T@B
BTB

Matrix([
[3, 3],
[3, 5]])

In [130]:
lamda = BTB.inv()@BTx
lamda

Matrix([
[10],
[-6]])

In [131]:
proj = lamda[0]*b1 + lamda[1]*b2
proj

Matrix([
[10],
[ 4],
[-2]])